- name: Job Market Interventions
  image: service1.svg
- name: Hand Holding Job Seekers
  image: service-2.svg
- name: Career, Growth And Job Rehabilitation Schema
  image: service-3.svg
- name: Recruitment Drives And Job Fairs
  image: service-4.svg
- name: Multimodal Job Bank Portal (www.thejobbank.in)
  image: service-5.svg
- name: References For Bank Loans
  image: service-6.svg
